package labs.claucookie.pasbuk.data.mapper

import com.squareup.moshi.Moshi
import labs.claucookie.pasbuk.data.local.entity.JourneyEntity
import labs.claucookie.pasbuk.data.local.entity.JourneyWithPasses
import labs.claucookie.pasbuk.domain.model.Journey
import labs.claucookie.pasbuk.domain.model.Pass
import java.time.Instant

/**
 * Extension function to convert JourneyEntity to Journey domain model.
 * Note: This creates a Journey with an empty passes list.
 * Use JourneyWithPasses.toDomain() for full journey with passes.
 */
fun JourneyEntity.toDomain(): Journey {
    return Journey(
        id = id,
        name = name,
        passes = emptyList(),
        createdAt = Instant.ofEpochMilli(createdAt),
        modifiedAt = Instant.ofEpochMilli(modifiedAt)
    )
}

/**
 * Extension function to convert JourneyWithPasses to Journey domain model.
 * Passes are sorted by relevantDate (ascending) as per spec.
 */
fun JourneyWithPasses.toDomain(moshi: Moshi): Journey {
    val domainPasses = passes
        .map { it.toDomain(moshi) }
        .sortedBy { it.relevantDate }

    return Journey(
        id = journey.id,
        name = journey.name,
        passes = domainPasses,
        createdAt = Instant.ofEpochMilli(journey.createdAt),
        modifiedAt = Instant.ofEpochMilli(journey.modifiedAt)
    )
}

/**
 * Extension function to convert Journey domain model to JourneyEntity.
 * Note: This does not include pass relationships - those are managed via JourneyPassCrossRef.
 */
fun Journey.toEntity(): JourneyEntity {
    return JourneyEntity(
        id = id,
        name = name,
        createdAt = createdAt.toEpochMilli(),
        modifiedAt = modifiedAt.toEpochMilli()
    )
}

/**
 * Creates a new JourneyEntity from domain parameters.
 * Use this when creating a new journey (id will be auto-generated).
 */
fun createJourneyEntity(
    name: String,
    createdAt: Instant = Instant.now(),
    modifiedAt: Instant = Instant.now()
): JourneyEntity {
    return JourneyEntity(
        id = 0, // Auto-generated by Room
        name = name,
        createdAt = createdAt.toEpochMilli(),
        modifiedAt = modifiedAt.toEpochMilli()
    )
}
