package labs.claucookie.pasbuk.data.mapper

import com.squareup.moshi.Moshi
import com.squareup.moshi.Types
import labs.claucookie.pasbuk.data.local.entity.JourneyEntity
import labs.claucookie.pasbuk.data.local.entity.JourneyWithPasses
import labs.claucookie.pasbuk.domain.model.ActivitySuggestion
import labs.claucookie.pasbuk.domain.model.Journey
import labs.claucookie.pasbuk.domain.model.Pass
import java.time.Instant

/**
 * Extension function to convert JourneyEntity to Journey domain model.
 * Note: This creates a Journey with an empty passes list.
 * Use JourneyWithPasses.toDomain() for full journey with passes.
 */
fun JourneyEntity.toDomain(moshi: Moshi): Journey {
    val suggestions = deserializeSuggestions(suggestionsJson, moshi)

    return Journey(
        id = id,
        name = name,
        passes = emptyList(),
        suggestions = suggestions,
        createdAt = Instant.ofEpochMilli(createdAt),
        modifiedAt = Instant.ofEpochMilli(modifiedAt)
    )
}

/**
 * Extension function to convert JourneyWithPasses to Journey domain model.
 * Passes are sorted by relevantDate (ascending) as per spec.
 */
fun JourneyWithPasses.toDomain(moshi: Moshi): Journey {
    val domainPasses = passes
        .map { it.toDomain(moshi) }
        .sortedBy { it.relevantDate }

    val suggestions = deserializeSuggestions(journey.suggestionsJson, moshi)

    return Journey(
        id = journey.id,
        name = journey.name,
        passes = domainPasses,
        suggestions = suggestions,
        createdAt = Instant.ofEpochMilli(journey.createdAt),
        modifiedAt = Instant.ofEpochMilli(journey.modifiedAt)
    )
}

/**
 * Extension function to convert Journey domain model to JourneyEntity.
 * Note: This does not include pass relationships - those are managed via JourneyPassCrossRef.
 */
fun Journey.toEntity(moshi: Moshi): JourneyEntity {
    val suggestionsJson = serializeSuggestions(suggestions, moshi)

    return JourneyEntity(
        id = id,
        name = name,
        suggestionsJson = suggestionsJson,
        createdAt = createdAt.toEpochMilli(),
        modifiedAt = modifiedAt.toEpochMilli()
    )
}

/**
 * Creates a new JourneyEntity from domain parameters.
 * Use this when creating a new journey (id will be auto-generated).
 */
fun createJourneyEntity(
    name: String,
    createdAt: Instant = Instant.now(),
    modifiedAt: Instant = Instant.now()
): JourneyEntity {
    return JourneyEntity(
        id = 0, // Auto-generated by Room
        name = name,
        suggestionsJson = null,
        createdAt = createdAt.toEpochMilli(),
        modifiedAt = modifiedAt.toEpochMilli()
    )
}

/**
 * Deserializes suggestions from JSON string.
 * Returns empty list if JSON is null or parsing fails.
 */
private fun deserializeSuggestions(json: String?, moshi: Moshi): List<ActivitySuggestion> {
    if (json.isNullOrBlank()) return emptyList()

    return try {
        val adapter = moshi.adapter<List<ActivitySuggestion>>(
            Types.newParameterizedType(List::class.java, ActivitySuggestion::class.java)
        )
        adapter.fromJson(json) ?: emptyList()
    } catch (e: Exception) {
        emptyList()
    }
}

/**
 * Serializes suggestions to JSON string.
 * Returns null if list is empty.
 */
private fun serializeSuggestions(suggestions: List<ActivitySuggestion>, moshi: Moshi): String? {
    if (suggestions.isEmpty()) return null

    return try {
        val adapter = moshi.adapter<List<ActivitySuggestion>>(
            Types.newParameterizedType(List::class.java, ActivitySuggestion::class.java)
        )
        adapter.toJson(suggestions)
    } catch (e: Exception) {
        null
    }
}
